contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #taxprofiler channel"
    url: https://nfcore.slack.com/channels/taxprofiler
    about: Discussion about the nf-core/taxprofiler pipeline
